//
// HomeControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class HomeControllerAPI {
    /**
     dashboard
     
     - parameter accountId: (path) accountId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func dashboardUsingGET(accountId: Int64, completion: @escaping ((_ data: [DashboardDTO]?,_ error: Error?) -> Void)) {
        dashboardUsingGETWithRequestBuilder(accountId: accountId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     dashboard
     - GET /dashboard/{accountId}
     - examples: [{output=none}]
     
     - parameter accountId: (path) accountId 

     - returns: RequestBuilder<[DashboardDTO]> 
     */
    open class func dashboardUsingGETWithRequestBuilder(accountId: Int64) -> RequestBuilder<[DashboardDTO]> {
        var path = "/dashboard/{accountId}"
        path = path.replacingOccurrences(of: "{accountId}", with: "\(accountId)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[DashboardDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
