//
// SAccountControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SAccountControllerAPI {
    /**
     get
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUsingGET1(completion: @escaping ((_ data: [SAccount]?,_ error: Error?) -> Void)) {
        getUsingGET1WithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     get
     - GET /sAccounts
     - examples: [{output=none}]

     - returns: RequestBuilder<[SAccount]> 
     */
    open class func getUsingGET1WithRequestBuilder() -> RequestBuilder<[SAccount]> {
        let path = "/sAccounts"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[SAccount]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
