//
// SChat2ControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SChat2ControllerAPI {
    /**
     getOne
     
     - parameter id: (path) id 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getOneUsingGET1(id: Int64, completion: @escaping ((_ data: SMessage2?,_ error: Error?) -> Void)) {
        getOneUsingGET1WithRequestBuilder(id: id).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     getOne
     - GET /sMessage2s/{id}
     - examples: [{output=none}]
     
     - parameter id: (path) id 

     - returns: RequestBuilder<SMessage2> 
     */
    open class func getOneUsingGET1WithRequestBuilder(id: Int64) -> RequestBuilder<SMessage2> {
        var path = "/sMessage2s/{id}"
        path = path.replacingOccurrences(of: "{id}", with: "\(id)", options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SMessage2>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     pull
     
     - parameter conversationId: (query) conversationId 
     - parameter lastMsgId: (query) lastMsgId 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func pullUsingGET(conversationId: Int64, lastMsgId: Int64, completion: @escaping ((_ data: [SMessage2]?,_ error: Error?) -> Void)) {
        pullUsingGETWithRequestBuilder(conversationId: conversationId, lastMsgId: lastMsgId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     pull
     - GET /sMessage2s
     - examples: [{output=none}]
     
     - parameter conversationId: (query) conversationId 
     - parameter lastMsgId: (query) lastMsgId 

     - returns: RequestBuilder<[SMessage2]> 
     */
    open class func pullUsingGETWithRequestBuilder(conversationId: Int64, lastMsgId: Int64) -> RequestBuilder<[SMessage2]> {
        let path = "/sMessage2s"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)
        url?.queryItems = APIHelper.mapValuesToQueryItems(values:[
            "conversationId": conversationId.encodeToJSON(), 
            "lastMsgId": lastMsgId.encodeToJSON()
        ])
        

        let requestBuilder: RequestBuilder<[SMessage2]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

    /**
     push
     
     - parameter sMessageDTO: (body) sMessageDTO 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func pushUsingPOST(sMessageDTO: SMessageDTO, completion: @escaping ((_ data: SMessage2?,_ error: Error?) -> Void)) {
        pushUsingPOSTWithRequestBuilder(sMessageDTO: sMessageDTO).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     push
     - POST /sMessage2s
     - examples: [{output=none}]
     
     - parameter sMessageDTO: (body) sMessageDTO 

     - returns: RequestBuilder<SMessage2> 
     */
    open class func pushUsingPOSTWithRequestBuilder(sMessageDTO: SMessageDTO) -> RequestBuilder<SMessage2> {
        let path = "/sMessage2s"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: sMessageDTO)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SMessage2>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

}
