//
// SMiniCoinPoolControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SMiniCoinPoolControllerAPI {
    /**
     add
     
     - parameter m: (body) m 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func addUsingPOST(m: SMiniCoinPoolDTO, completion: @escaping ((_ data: SMiniCoinPool?,_ error: Error?) -> Void)) {
        addUsingPOSTWithRequestBuilder(m: m).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     add
     - POST /miniCoinPools
     - examples: [{output=none}]
     
     - parameter m: (body) m 

     - returns: RequestBuilder<SMiniCoinPool> 
     */
    open class func addUsingPOSTWithRequestBuilder(m: SMiniCoinPoolDTO) -> RequestBuilder<SMiniCoinPool> {
        let path = "/miniCoinPools"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: m)

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<SMiniCoinPool>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }

    /**
     get
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUsingGET2(completion: @escaping ((_ data: [SMiniCoinPool]?,_ error: Error?) -> Void)) {
        getUsingGET2WithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     get
     - GET /miniCoinPools
     - examples: [{output=none}]

     - returns: RequestBuilder<[SMiniCoinPool]> 
     */
    open class func getUsingGET2WithRequestBuilder() -> RequestBuilder<[SMiniCoinPool]> {
        let path = "/miniCoinPools"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[SMiniCoinPool]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
