//
// SMiniContractControllerAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class SMiniContractControllerAPI {
    /**
     get
     
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func getUsingGET3(completion: @escaping ((_ data: [SMiniContract]?,_ error: Error?) -> Void)) {
        getUsingGET3WithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     get
     - GET /
     - examples: [{output=none}]

     - returns: RequestBuilder<[SMiniContract]> 
     */
    open class func getUsingGET3WithRequestBuilder() -> RequestBuilder<[SMiniContract]> {
        let path = "/"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[SMiniContract]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
