//
// AddFriendDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class AddFriendDTO: Codable {

    public var accountId: Int64?
    public var friendId: Int64?


    
    public init(accountId: Int64?, friendId: Int64?) {
        self.accountId = accountId
        self.friendId = friendId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(accountId, forKey: "accountId")
        try container.encodeIfPresent(friendId, forKey: "friendId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        accountId = try container.decodeIfPresent(Int64.self, forKey: "accountId")
        friendId = try container.decodeIfPresent(Int64.self, forKey: "friendId")
    }
}

