//
// Link.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Link: Codable {

    public var href: String?
    public var rel: String?
    public var templated: Bool?


    
    public init(href: String?, rel: String?, templated: Bool?) {
        self.href = href
        self.rel = rel
        self.templated = templated
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(href, forKey: "href")
        try container.encodeIfPresent(rel, forKey: "rel")
        try container.encodeIfPresent(templated, forKey: "templated")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        href = try container.decodeIfPresent(String.self, forKey: "href")
        rel = try container.decodeIfPresent(String.self, forKey: "rel")
        templated = try container.decodeIfPresent(Bool.self, forKey: "templated")
    }
}

