//
// SCouponOwnerDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SCouponOwnerDTO: Codable {

    public var receiver: Int64?
    public var important: Bool?


    
    public init(receiver: Int64?, important: Bool?) {
        self.receiver = receiver
        self.important = important
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(receiver, forKey: "receiver")
        try container.encodeIfPresent(important, forKey: "important")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        receiver = try container.decodeIfPresent(Int64.self, forKey: "receiver")
        important = try container.decodeIfPresent(Bool.self, forKey: "important")
    }
}

