//
// SCouponDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SCouponDTO: Codable {

    public enum CouponType: String, Codable { 
        case 满减 = "满减"
        case 抵用 = "抵用"
        case 折扣 = "折扣"
        case 兑换 = "兑换"
    }
    /** 抵用数量 */
    public var amount: Int64?
    /** 减多少 */
    public var cut: Int64?
    /** 折扣 */
    public var discount: Int64?
    /** 过期日期 */
    public var expiredAt: Int64?
    /** 满多少 */
    public var full: Int64?
    /** 兑换物品图片url */
    public var goodsUrl: String?
    /** 是否已经发行 */
    public var issued: Bool?
    /** 图标 */
    public var logo: String?
    /** 名称 */
    public var name: String?
    /** 备注 */
    public var remarks: String?
    public var creator: Int64?
    public var couponType: CouponType?


    
    public init(amount: Int64?, cut: Int64?, discount: Int64?, expiredAt: Int64?, full: Int64?, goodsUrl: String?, issued: Bool?, logo: String?, name: String?, remarks: String?, creator: Int64?, couponType: CouponType?) {
        self.amount = amount
        self.cut = cut
        self.discount = discount
        self.expiredAt = expiredAt
        self.full = full
        self.goodsUrl = goodsUrl
        self.issued = issued
        self.logo = logo
        self.name = name
        self.remarks = remarks
        self.creator = creator
        self.couponType = couponType
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(amount, forKey: "amount")
        try container.encodeIfPresent(cut, forKey: "cut")
        try container.encodeIfPresent(discount, forKey: "discount")
        try container.encodeIfPresent(expiredAt, forKey: "expiredAt")
        try container.encodeIfPresent(full, forKey: "full")
        try container.encodeIfPresent(goodsUrl, forKey: "goodsUrl")
        try container.encodeIfPresent(issued, forKey: "issued")
        try container.encodeIfPresent(logo, forKey: "logo")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(remarks, forKey: "remarks")
        try container.encodeIfPresent(creator, forKey: "creator")
        try container.encodeIfPresent(couponType, forKey: "couponType")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        amount = try container.decodeIfPresent(Int64.self, forKey: "amount")
        cut = try container.decodeIfPresent(Int64.self, forKey: "cut")
        discount = try container.decodeIfPresent(Int64.self, forKey: "discount")
        expiredAt = try container.decodeIfPresent(Int64.self, forKey: "expiredAt")
        full = try container.decodeIfPresent(Int64.self, forKey: "full")
        goodsUrl = try container.decodeIfPresent(String.self, forKey: "goodsUrl")
        issued = try container.decodeIfPresent(Bool.self, forKey: "issued")
        logo = try container.decodeIfPresent(String.self, forKey: "logo")
        name = try container.decodeIfPresent(String.self, forKey: "name")
        remarks = try container.decodeIfPresent(String.self, forKey: "remarks")
        creator = try container.decodeIfPresent(Int64.self, forKey: "creator")
        couponType = try container.decodeIfPresent(CouponType.self, forKey: "couponType")
    }
}

