//
// SendSMembershipDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SendSMembershipDTO: Codable {

    public var accountIds: [Int64]?
    public var expiredAt: Int64?


    
    public init(accountIds: [Int64]?, expiredAt: Int64?) {
        self.accountIds = accountIds
        self.expiredAt = expiredAt
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(accountIds, forKey: "accountIds")
        try container.encodeIfPresent(expiredAt, forKey: "expiredAt")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        accountIds = try container.decodeIfPresent([Int64].self, forKey: "accountIds")
        expiredAt = try container.decodeIfPresent(Int64.self, forKey: "expiredAt")
    }
}

