//
// SendSCouponDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SendSCouponDTO: Codable {

    public var receivers: [SCouponReceiverDTO]?
    public var expiredAt: Int64?
    public var transferable: Bool?


    
    public init(receivers: [SCouponReceiverDTO]?, expiredAt: Int64?, transferable: Bool?) {
        self.receivers = receivers
        self.expiredAt = expiredAt
        self.transferable = transferable
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(receivers, forKey: "receivers")
        try container.encodeIfPresent(expiredAt, forKey: "expiredAt")
        try container.encodeIfPresent(transferable, forKey: "transferable")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        receivers = try container.decodeIfPresent([SCouponReceiverDTO].self, forKey: "receivers")
        expiredAt = try container.decodeIfPresent(Int64.self, forKey: "expiredAt")
        transferable = try container.decodeIfPresent(Bool.self, forKey: "transferable")
    }
}

