//
// SMembership.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SMembership: Codable {

    public enum MembershipType: String, Codable { 
        case vip = "VIP"
        case work = "Work"
        case studentID = "StudentID"
    }
    public var activated: Bool?
    public var createTime: Int64?
    public var creator: SAccount?
    public var expireAt: Int64?
    public var id: Int64?
    public var issuedNum: Int64?
    public var lastModifyTime: Int64?
    public var logo: String?
    public var membershipType: MembershipType?
    public var name: String?
    public var remarks: String?
    public var version: Int64?


    
    public init(activated: Bool?, createTime: Int64?, creator: SAccount?, expireAt: Int64?, id: Int64?, issuedNum: Int64?, lastModifyTime: Int64?, logo: String?, membershipType: MembershipType?, name: String?, remarks: String?, version: Int64?) {
        self.activated = activated
        self.createTime = createTime
        self.creator = creator
        self.expireAt = expireAt
        self.id = id
        self.issuedNum = issuedNum
        self.lastModifyTime = lastModifyTime
        self.logo = logo
        self.membershipType = membershipType
        self.name = name
        self.remarks = remarks
        self.version = version
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(activated, forKey: "activated")
        try container.encodeIfPresent(createTime, forKey: "createTime")
        try container.encodeIfPresent(creator, forKey: "creator")
        try container.encodeIfPresent(expireAt, forKey: "expireAt")
        try container.encodeIfPresent(id, forKey: "id")
        try container.encodeIfPresent(issuedNum, forKey: "issuedNum")
        try container.encodeIfPresent(lastModifyTime, forKey: "lastModifyTime")
        try container.encodeIfPresent(logo, forKey: "logo")
        try container.encodeIfPresent(membershipType, forKey: "membershipType")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(remarks, forKey: "remarks")
        try container.encodeIfPresent(version, forKey: "version")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        activated = try container.decodeIfPresent(Bool.self, forKey: "activated")
        createTime = try container.decodeIfPresent(Int64.self, forKey: "createTime")
        creator = try container.decodeIfPresent(SAccount.self, forKey: "creator")
        expireAt = try container.decodeIfPresent(Int64.self, forKey: "expireAt")
        id = try container.decodeIfPresent(Int64.self, forKey: "id")
        issuedNum = try container.decodeIfPresent(Int64.self, forKey: "issuedNum")
        lastModifyTime = try container.decodeIfPresent(Int64.self, forKey: "lastModifyTime")
        logo = try container.decodeIfPresent(String.self, forKey: "logo")
        membershipType = try container.decodeIfPresent(MembershipType.self, forKey: "membershipType")
        name = try container.decodeIfPresent(String.self, forKey: "name")
        remarks = try container.decodeIfPresent(String.self, forKey: "remarks")
        version = try container.decodeIfPresent(Int64.self, forKey: "version")
    }
}

