//
// SMiniContractConversationDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SMiniContractConversationDTO: Codable {

    public var creator: Int64?
    public var name: String?
    public var partner: Int64?
    public var sminiContractId: Int64?


    
    public init(creator: Int64?, name: String?, partner: Int64?, sminiContractId: Int64?) {
        self.creator = creator
        self.name = name
        self.partner = partner
        self.sminiContractId = sminiContractId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(creator, forKey: "creator")
        try container.encodeIfPresent(name, forKey: "name")
        try container.encodeIfPresent(partner, forKey: "partner")
        try container.encodeIfPresent(sminiContractId, forKey: "sminiContractId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        creator = try container.decodeIfPresent(Int64.self, forKey: "creator")
        name = try container.decodeIfPresent(String.self, forKey: "name")
        partner = try container.decodeIfPresent(Int64.self, forKey: "partner")
        sminiContractId = try container.decodeIfPresent(Int64.self, forKey: "sminiContractId")
    }
}

