//
// SMiniCoinDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class SMiniCoinDTO: Codable {

    public var ownerId: Int64?


    
    public init(ownerId: Int64?) {
        self.ownerId = ownerId
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(ownerId, forKey: "ownerId")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        ownerId = try container.decodeIfPresent(Int64.self, forKey: "ownerId")
    }
}

