//
// View.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class View: Codable {

    public var contentType: String?


    
    public init(contentType: String?) {
        self.contentType = contentType
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encodeIfPresent(contentType, forKey: "contentType")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        contentType = try container.decodeIfPresent(String.self, forKey: "contentType")
    }
}

